//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOTAS
    {
        public decimal NUMEROCUOTA { get; set; }
        public Nullable<decimal> FK_NUMEROSOCIO { get; set; }
        public Nullable<System.DateTime> MESPAGO { get; set; }
        public Nullable<System.DateTime> FECHAPAGO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual SOCIOS SOCIOS { get; set; }
    }
}
