//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIOS
    {
        public SOCIOS()
        {
            this.CUOTAS = new HashSet<CUOTAS>();
        }
    
        public decimal NUMEROSOCIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> FONO { get; set; }
        public string PATENTE { get; set; }
        public string MODELO { get; set; }
        public string MARCA { get; set; }
        public Nullable<decimal> ANIO { get; set; }
        public string FOTO { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual ICollection<CUOTAS> CUOTAS { get; set; }
    }
}
